package com.dahantc.erp.commom.warn;

public enum TriggerType {
	TRIGGER_DATABASE_ERROR, TRIGGER_CHANNEL_ERROR, TRIGGER_CTCSERVER_ERROR, TRIGGER_SMSMT_ERROR, TRIGGER_MMSMT_ERROR, TRIGGER_TOPG_ERROR
}
